function thickData = prepareGCThickData()
% Script to take the GC thickness profile generated by retinaTOMEAnalysis
% and turn it into a file suitable for analysis by this repo.

% Find and load the files we need
dropboxBaseDir = getpref('rgcPopulationModel','dropboxBaseDir');
rawDataFile = fullfile(dropboxBaseDir, 'AOSO_analysis','OCTExplorerExtendedHorizontalData','LineAnalysisResults.mat');
filepath = fileparts(mfilename('fullpath'));
filepath = strrep(filepath,'code','data');
mmPerDegPolyFitFile = fullfile(filepath,'mmPerDegPolyFitEmmetrope.mat');
load(mmPerDegPolyFitFile,'mmPerDegPolyFit');
load(rawDataFile,'meanPC1','XPos_Degs');

% Convert the volume data to thickness

mmSqPerDegSq = mmPerDegPolyFit([zeros(size(XPos_Degs));-XPos_Degs]').^2;
gcThickness = meanPC1./mmSqPerDegSq;

thickData(1).label = 'temporal';
thickData(1).angle = 180;
thickData(1).supportDeg = abs(XPos_Degs(XPos_Degs<=0));
thickData(1).thickMM = (gcThickness(XPos_Degs<=0)'./1000)';

thickData(2).label = 'nasal';
thickData(2).angle = 0;
thickData(2).supportDeg = abs(XPos_Degs(XPos_Degs>=0));
thickData(2).thickMM = (gcThickness(XPos_Degs>=0)'./1000)';

end