function thickData = prepareGCThickData()

% Script to take the GC thickness profile generated by retinaTOMEAnalysis
% and turn it into a file suitable for analysis by this repo.

rawDataFile = '/Users/aguirre/Dropbox (Aguirre-Brainard Lab)/AOSO_analysis/OCTExplorerExtendedHorizontalData/LineAnalysisResults.mat';
load(rawDataFile,'meanGCVec','XPos_Degs');

thickData(1).label = 'temporal';
thickData(1).angle = 180;
thickData(1).supportDeg = abs(XPos_Degs(XPos_Degs<=0));
thickData(1).thickMM = (meanGCVec(XPos_Degs<=0)'./1000)';

thickData(2).label = 'nasal';
thickData(2).angle = 0;
thickData(2).supportDeg = abs(XPos_Degs(XPos_Degs>=0));
thickData(2).thickMM = (meanGCVec(XPos_Degs>=0)'./1000)';

end